import 'dart:io';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('Code Size & Static Analysis', () {
    test('Measure Dart code size and complexity', () {
      print('\n========================================');
      print('  CODE SIZE ANALYSIS');
      print('========================================');

      final libDir = Directory('lib');
      if (!libDir.existsSync()) {
        print('lib/ directory not found');
        return;
      }

      final dartFiles = libDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.endsWith('.dart') && !f.path.contains('.g.dart'))
          .toList();

      int totalLines = 0;
      int totalFiles = dartFiles.length;
      final fileLines = <String, int>{};

      for (final file in dartFiles) {
        final lines = file.readAsLinesSync();
        final nonEmpty = lines.where((l) => l.trim().isNotEmpty).length;
        final relativePath = file.path.replaceFirst('lib/', '');
        fileLines[relativePath] = nonEmpty;
        totalLines += nonEmpty;
      }

      final sorted = fileLines.entries.toList()
        ..sort((a, b) => b.value.compareTo(a.value));

      print('\n--- File Size Ranking (Top 15) ---');
      final top = sorted.length > 15 ? sorted.sublist(0, 15) : sorted;
      for (final entry in top) {
        final bar = '█' * (entry.value ~/ 10);
        print('  ${entry.key.padRight(45)} ${entry.value.toString().padLeft(5)} lines  $bar');
      }

      print('\n--- Summary ---');
      print('  Total Dart files:     $totalFiles');
      print('  Total lines of code:  $totalLines');
      print('  Average lines/file:   ${(totalLines / totalFiles).toStringAsFixed(0)}');

      final largeFiles = sorted.where((e) => e.value > 200).toList();
      if (largeFiles.isNotEmpty) {
        print('\n--- Large Files (>200 lines) ---');
        for (final entry in largeFiles) {
          print('  ⚠ ${entry.key}: ${entry.value} lines');
        }
        print('  Consider splitting large files into smaller, focused modules.');
      }

      print('\n--- Empty Directories ---');
      final emptyDirs = <String>[];
      for (final entity in libDir.listSync(recursive: true)) {
        if (entity is Directory) {
          final contents = entity.listSync().where((e) => !e.path.endsWith('.dart')).toList();
          final dartFilesInDir = entity.listSync().where((f) => f.path.endsWith('.dart')).toList();
          if (dartFilesInDir.isEmpty && contents.isEmpty) {
            emptyDirs.add(entity.path.replaceFirst('lib/', 'lib/'));
          }
        }
      }
      if (emptyDirs.isNotEmpty) {
        for (final dir in emptyDirs) {
          print('  ⚠ Empty: $dir');
        }
        print('  Remove empty directories to reduce clutter.');
      } else {
        print('  No empty directories found.');
      }

      print('\n--- Generated Files ---');
      final generatedFiles = libDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.contains('.g.dart'))
          .toList();
      int generatedLines = 0;
      for (final file in generatedFiles) {
        generatedLines += file.readAsLinesSync().length;
      }
      print('  Generated files: ${generatedFiles.length}');
      print('  Generated lines: $generatedLines');
      print('  (These are auto-generated by build_runner, do not edit manually)');
      print('========================================\n');
    });

    test('Check for const constructor opportunities', () {
      print('\n========================================');
      print('  CONST CONSTRUCTOR ANALYSIS');
      print('========================================');

      final libDir = Directory('lib');
      if (!libDir.existsSync()) return;

      final dartFiles = libDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.endsWith('.dart') && !f.path.contains('.g.dart'))
          .toList();

      int constWidgets = 0;
      int nonConstWidgets = 0;
      final suggestions = <String>[];

      for (final file in dartFiles) {
        final content = file.readAsLinesSync();
        final relativePath = file.path.replaceFirst('lib/', '');
        for (int i = 0; i < content.length; i++) {
          final line = content[i];
          if (line.contains('const ') && line.contains('Widget')) {
            constWidgets++;
          }
          if (line.contains('return ') &&
              (line.contains('Container(') ||
                  line.contains('Padding(') ||
                  line.contains('Center(') ||
                  line.contains('SizedBox(')) &&
              !line.contains('const ')) {
            nonConstWidgets++;
            if (suggestions.length < 5) {
              suggestions.add('$relativePath:${i + 1}: Consider adding const');
            }
          }
        }
      }

      print('\n  Const widgets:    $constWidgets');
      print('  Non-const found:  $nonConstWidgets');
      if (suggestions.isNotEmpty) {
        print('\n  Top optimization opportunities:');
        for (final s in suggestions) {
          print('    → $s');
        }
      }
      print('========================================\n');
    });

    test('Analyze import dependencies for circular refs', () {
      print('\n========================================');
      print('  IMPORT DEPENDENCY MAP');
      print('========================================');

      final libDir = Directory('lib');
      if (!libDir.existsSync()) return;

      final dartFiles = libDir
          .listSync(recursive: true)
          .whereType<File>()
          .where((f) => f.path.endsWith('.dart') && !f.path.contains('.g.dart'))
          .toList();

      final importMap = <String, List<String>>{};

      for (final file in dartFiles) {
        final content = file.readAsStringSync();
        final relativePath = file.path.replaceFirst('lib/', '');
        final imports = <String>[];

        for (final match in RegExp(r"import\s+'package:gallerio/([^']+)'" ).allMatches(content)) {
          imports.add(match.group(1)!);
        }
        for (final match in RegExp(r"import\s+'(\.\./[^']+|\.\/[^']+)'" ).allMatches(content)) {
          imports.add(match.group(1)!);
        }
        importMap[relativePath] = imports;
      }

      final featureImports = <String, int>{};
      for (final entry in importMap.entries) {
        for (final imp in entry.value) {
          final feature = imp.split('/').first;
          featureImports[feature] = (featureImports[feature] ?? 0) + 1;
        }
      }

      print('\n--- Feature Import Frequency ---');
      final sorted = featureImports.entries.toList()
        ..sort((a, b) => b.value.compareTo(a.value));
      for (final entry in sorted) {
        print('  ${entry.key.padRight(20)} imported ${entry.value} times');
      }

      print('\n--- Cross-Feature Dependencies ---');
      final crossFeature = <String, List<String>>{};
      for (final entry in importMap.entries) {
        final sourceFeature = entry.key.split('/').first;
        for (final imp in entry.value) {
          final targetFeature = imp.split('/').first;
          if (sourceFeature != targetFeature &&
              !sourceFeature.contains('shared') &&
              !targetFeature.contains('shared')) {
            final key = '$sourceFeature → $targetFeature';
            crossFeature.putIfAbsent(key, () => []);
            crossFeature[key]!.add(entry.key);
          }
        }
      }

      if (crossFeature.isEmpty) {
        print('  No cross-feature dependencies. Clean architecture!');
      } else {
        for (final entry in crossFeature.entries) {
          print('  ⚠ ${entry.key} (${entry.value.length} files)');
        }
      }
      print('========================================\n');
    });
  });
}
